import { defineAction } from 'redux-define';
import SUB_ACTIONS_TYPES from '../constants';

const SIGNUP_USER = defineAction('SIGNUP_USER', SUB_ACTIONS_TYPES);
const FORGOT_PASS_USER = defineAction('FORGOT_PASS_USER', SUB_ACTIONS_TYPES);
const СHECK_TOKEN_CHANGE_PASS_USER = defineAction('СHECK_TOKEN_CHANGE_PASS_USER', SUB_ACTIONS_TYPES);
const CHANGE_PASS_USER = defineAction('CHANGE_PASS_USER', SUB_ACTIONS_TYPES);
export default {
  SIGNUP_USER, FORGOT_PASS_USER, СHECK_TOKEN_CHANGE_PASS_USER, CHANGE_PASS_USER,
};
